sudo: required
dist: trusty
matrix:
  include:
    - language: python
      python: 2.7
      before_install:
        - cd deployment
      install:
        - pip install paramiko pyyaml jinja2 python-etcd kubernetes
      script:
        - python -m unittest discover test/

    - language: python
      python: 2.7
      before_install:
        - cd src/watchdog/test
      install:
        - pip install paramiko pyyaml requests prometheus_client
      script:
        - python -m unittest discover .

    - language: python
      python: 2.7
      before_install:
        - cd src/job-exporter/test
      install:
        - pip install pyyaml
      script:
        - python -m unittest discover .

    - language: python
      python: 2.7
      install:
        - pip install markdown==2.6.11
      script:
        - python src/utilities/doc_checker.py .

    - language: java
      jdk: oraclejdk8
      before_install:
        - cd subprojects/frameworklauncher/yarn
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn clean test jacoco:report coveralls:report

    - language: java
      jdk: openjdk8
      before_install:
        - cd subprojects/frameworklauncher/yarn
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn clean test jacoco:report coveralls:report

    - language: node_js
      node_js: lts/carbon
      env: NODE_ENV=test
      before_install:
        - cd src/rest-server
      install:
        - npm install
      script:
        - npm test
        - npm run coveralls

    - language: node_js
      node_js: node
      env: NODE_ENV=test
      before_install:
        - cd src/rest-server
      install:
        - npm install
      script:
        - npm test
        - npm run coveralls

    - language: node_js
      node_js: lts/carbon
      before_install:
        - cd src/webportal
      install:
        - yarn install
        - npm run build
      script:
        - npm test

    - language: node_js
      node_js: node
      before_install:
        - cd src/webportal
      install:
        - yarn install
        - npm run build
      script:
        - npm test
